/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2proje;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yusuf
 */
public class Faturasayfasi extends javax.swing.JFrame {
    
private String kullaniciTuru;
    /**
     * Creates new form Faturasayfasi
     */
   public Faturasayfasi() {
       this.kullaniciTuru = "standart";
    initComponents();
    loadFaturaVerileri();
    
}
   public Faturasayfasi(String kullaniciTuru) {
     this.kullaniciTuru = kullaniciTuru;
    System.out.println("Faturasayfasi oluşturuldu: Kullanıcı Türü = " + this.kullaniciTuru);
    initComponents();
    loadFaturaVerileri();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        siparisveregeridon = new javax.swing.JButton();
        toplamkazancigosterbutonu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ürün Adı", "Miktarı", "Ödeme Yöntemi", "Ödenen Tutar"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        siparisveregeridon.setBackground(new java.awt.Color(0, 51, 153));
        siparisveregeridon.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        siparisveregeridon.setForeground(new java.awt.Color(255, 255, 255));
        siparisveregeridon.setText("Sipariş Verme Ekranına Dön");
        siparisveregeridon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siparisveregeridonActionPerformed(evt);
            }
        });

        toplamkazancigosterbutonu.setBackground(new java.awt.Color(0, 51, 153));
        toplamkazancigosterbutonu.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        toplamkazancigosterbutonu.setForeground(new java.awt.Color(255, 255, 255));
        toplamkazancigosterbutonu.setText("Toplam Kazancı Gör");
        toplamkazancigosterbutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toplamkazancigosterbutonuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fatura Sayfası");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(siparisveregeridon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toplamkazancigosterbutonu, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siparisveregeridon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toplamkazancigosterbutonu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(904, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadFaturaVerileri() {
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Tabloyu temizle

    try {
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/canteen?user=root&password=elbiz-2221221040");
        String query = "SELECT urunadi, urunmiktari, odemeyontemi, toplamfiyat FROM fatura";
        pstmt = conn.prepareStatement(query);
        rs = pstmt.executeQuery();

        while (rs.next()) {
            String urunAdi = rs.getString("urunadi");
            int urunMiktari = rs.getInt("urunmiktari");
            String odemeYontemi = rs.getString("odemeyontemi");
            double toplamFiyat = rs.getDouble("toplamfiyat");

            model.addRow(new Object[]{urunAdi, urunMiktari, odemeYontemi, toplamFiyat});
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Veriler yüklenirken hata oluştu: " + ex.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
    } finally {
        try {
            if (rs != null) rs.close();
            if (pstmt != null) pstmt.close();
            if (conn != null) conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Bağlantı kapatılırken hata oluştu: " + ex.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }
}
    
    
    private void siparisveregeridonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siparisveregeridonActionPerformed
     System.out.println("Kullanıcı Türü: " + kullaniciTuru);
    if ("admin".equals(kullaniciTuru)) {
        System.out.println("Admin için sipariş ekranına dönüyor...");
        sipraisver siparisFrame = new sipraisver(kullaniciTuru);
        siparisFrame.setLocationRelativeTo(null);
        siparisFrame.setVisible(true);
        this.dispose();
    } else if ("standart".equals(kullaniciTuru)) {
        System.out.println("Standart kullanıcı için program kapanıyor...");
        JOptionPane.showMessageDialog(this, "Sipariş süreci tamamlandı. Program kapatılıyor.", "Bilgilendirme", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }
    }//GEN-LAST:event_siparisveregeridonActionPerformed

    private void toplamkazancigosterbutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toplamkazancigosterbutonuActionPerformed
        // TODO add your handling code here:
         Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    double toplamKazanc = 0;

    try {
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/canteen?user=root&password=elbiz-2221221040");
        String query = "SELECT SUM(toplamfiyat) AS toplamKazanc FROM fatura";
        pstmt = conn.prepareStatement(query);
        rs = pstmt.executeQuery();

        if (rs.next()) {
            toplamKazanc = rs.getDouble("toplamKazanc");
        }

        JOptionPane.showMessageDialog(this, "Toplam Kazanç: " + toplamKazanc + " TL", "Toplam Kazanç", JOptionPane.INFORMATION_MESSAGE);

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Hata: " + ex.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
    } finally {
        try {
            if (rs != null) rs.close();
            if (pstmt != null) pstmt.close();
            if (conn != null) conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Bağlantı kapatılırken hata oluştu: " + ex.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_toplamkazancigosterbutonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Faturasayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Faturasayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Faturasayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Faturasayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Faturasayfasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton siparisveregeridon;
    private javax.swing.JButton toplamkazancigosterbutonu;
    // End of variables declaration//GEN-END:variables
}
