/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2proje;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author yusuf
 */
public class girisyap extends javax.swing.JFrame {

    /**
     * Creates new form girisyap
     */
    public girisyap() {
   
        initComponents();
         this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kullaniciaditxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sifretxt = new javax.swing.JPasswordField();
        kayitolbutonu = new javax.swing.JButton();
        girisyapbutonu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        okulnumarasitxt = new javax.swing.JTextField();
        robotkontrolkutusu = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Kullanıcı Adı");

        kullaniciaditxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciaditxtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Şifre");

        sifretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifretxtActionPerformed(evt);
            }
        });

        kayitolbutonu.setBackground(new java.awt.Color(0, 51, 153));
        kayitolbutonu.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        kayitolbutonu.setForeground(new java.awt.Color(255, 255, 255));
        kayitolbutonu.setText("Kayit Ol");
        kayitolbutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitolbutonuActionPerformed(evt);
            }
        });

        girisyapbutonu.setBackground(new java.awt.Color(0, 51, 153));
        girisyapbutonu.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        girisyapbutonu.setForeground(new java.awt.Color(255, 255, 255));
        girisyapbutonu.setText("Giriş yap");
        girisyapbutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisyapbutonuActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Okul Numarası");

        okulnumarasitxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okulnumarasitxtActionPerformed(evt);
            }
        });

        robotkontrolkutusu.setBackground(new java.awt.Color(0, 51, 153));
        robotkontrolkutusu.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        robotkontrolkutusu.setForeground(new java.awt.Color(255, 255, 255));
        robotkontrolkutusu.setText("Robot Değilim");
        robotkontrolkutusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                robotkontrolkutusuActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("KANTIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(robotkontrolkutusu)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(kullaniciaditxt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sifretxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(kayitolbutonu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(girisyapbutonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(okulnumarasitxt))))
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kullaniciaditxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sifretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(okulnumarasitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(robotkontrolkutusu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(girisyapbutonu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kayitolbutonu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void girisyapbutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisyapbutonuActionPerformed
        // "Robot Değilim" kutusunun işaretlenip işaretlenmediğini kontrol et
    if (!robotkontrolkutusu.isSelected()) {
        JOptionPane.showMessageDialog(this, "Lütfen 'Robot Değilim' kutusunu işaretleyiniz!", "Hata", JOptionPane.ERROR_MESSAGE);
        return; // Eğer kutu işaretlenmemişse işlemi durdur
    }

    String kullaniciAdi = kullaniciaditxt.getText(); // Kullanıcı adını al
    String sifre = new String(sifretxt.getPassword()); // Şifreyi al
    String okulNumarasi = okulnumarasitxt.getText(); // Okul numarasını al
    String kullaniciTuru = null; // Kullanıcı türü saklanacak

    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/canteen?user=root&password= "); // Bağlantıyı aç
        String sql = "SELECT kayitolmaturu FROM kayitolma WHERE kullaniciadi = ? AND sifre = ? AND okulnumarasi = ?";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, kullaniciAdi);
        pstmt.setString(2, sifre);
        pstmt.setString(3, okulNumarasi);

        ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            kullaniciTuru = rs.getString("kayitolmaturu"); // Kullanıcı türünü al
            JOptionPane.showMessageDialog(this, "Giriş başarılı!");

            // Yeni frame'e kullanıcı türü ile geçiş yap
            sipraisver siparisFrame = new sipraisver(kullaniciTuru);
            siparisFrame.setLocationRelativeTo(null);
            siparisFrame.setVisible(true);
            this.dispose(); // Mevcut frame'i kapat
        } else {
            JOptionPane.showMessageDialog(this, "Hatalı kullanıcı adı, şifre veya okul numarası!", "Hata", JOptionPane.ERROR_MESSAGE);
        }

        rs.close();
        pstmt.close();
        conn.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Veritabanı hatası: " + ex.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
    }  
        
        
        
    }//GEN-LAST:event_girisyapbutonuActionPerformed

    private void kayitolbutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitolbutonuActionPerformed
        // TODO add your handling code here:
        kayitol kayitFrame = new kayitol();
        kayitFrame.setLocationRelativeTo(null);

        kayitFrame.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_kayitolbutonuActionPerformed

    private void kullaniciaditxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciaditxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kullaniciaditxtActionPerformed

    private void sifretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sifretxtActionPerformed

    private void okulnumarasitxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okulnumarasitxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okulnumarasitxtActionPerformed

    private void robotkontrolkutusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_robotkontrolkutusuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_robotkontrolkutusuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(girisyap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(girisyap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(girisyap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(girisyap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new girisyap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton girisyapbutonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kayitolbutonu;
    private javax.swing.JTextField kullaniciaditxt;
    private javax.swing.JTextField okulnumarasitxt;
    private javax.swing.JCheckBox robotkontrolkutusu;
    private javax.swing.JPasswordField sifretxt;
    // End of variables declaration//GEN-END:variables
}

