/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2proje;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author yusuf
 */
public class kayitol extends javax.swing.JFrame {
    private static final String connectionString = "jdbc:mysql://localhost:3306/canteen?user=root&password= ";
    
    /**
     * Creates new form kayitol
     */
    public kayitol() {
        initComponents();
          setTitle("Kayıt Ekranı");
          this.setLocationRelativeTo(null);
    }
    @Override
public void setTitle(String title) {
    super.setTitle(title + " - Kantin Otomasyonu");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kayitolbutonu = new javax.swing.JButton();
        kullaniciaditxt = new javax.swing.JTextField();
        sifretxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        okulnumarasitxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mailadresitxt = new javax.swing.JTextField();
        comboboxtur = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Kullanici Adı");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Şifre");

        kayitolbutonu.setBackground(new java.awt.Color(0, 51, 153));
        kayitolbutonu.setFont(new java.awt.Font("Wide Latin", 2, 10)); // NOI18N
        kayitolbutonu.setForeground(new java.awt.Color(255, 255, 255));
        kayitolbutonu.setText("Kayıt Ol");
        kayitolbutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitolbutonuActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Okul Numarası");

        okulnumarasitxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okulnumarasitxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Okul Mail Adresi");

        comboboxtur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "standart", "admin" }));
        comboboxtur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxturActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kayıt Ol");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("Kullanıcı Türü");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sifretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(okulnumarasitxt, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addComponent(kullaniciaditxt))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mailadresitxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboboxtur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(kayitolbutonu)
                        .addGap(61, 61, 61))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(okulnumarasitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kullaniciaditxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sifretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mailadresitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxtur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(kayitolbutonu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jMenu1.setText("hareket");

        jMenuItem1.setText("giriş sayasına dön");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static boolean KullanıcıEkle(String okulnumarasi, String kullaniciadi, String sifre, String email, String kayitolmaturu) {
        boolean rval = true;
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(connectionString);
            Statement stmt = conn.createStatement();

            String query = "INSERT INTO kayitolma (okulnumarasi, kullaniciadi, sifre, email, kayitolmaturu) "
                    + "VALUES('" + okulnumarasi + "','" + kullaniciadi + "','" + sifre + "','" + email + "','" + kayitolmaturu + "')";

            stmt.executeUpdate(query);
            conn.close();
        } catch (SQLException ex) {
            rval = false;
            System.out.println("Error: " + ex.getMessage());
        }
        return rval;
    }
    private void kayitolbutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitolbutonuActionPerformed
        // Kullanıcıdan alınan veriler
    String okulnumarasi = okulnumarasitxt.getText();
    String kullaniciadi = kullaniciaditxt.getText();
    String sifre = sifretxt.getText();
    String email = mailadresitxt.getText();
    String kayitolmaturu = (String) comboboxtur.getSelectedItem();

    // Regex desenleri
    String okulNumarasiDeseni = "\\d+"; // Sadece sayılar
    String kullaniciAdiDeseni = "^[a-zA-Z0-9]+$"; // Özel karakter kabul edilmez
    String sifreDeseni = ".{3,}"; // En az 3 karakter
    String emailDeseni = "^[a-zA-Z0-9._%+-]+@stu\\.fsm\\.edu\\.tr$"; // Belirtilen mail formatı

    // Doğrulamalar
    if (!okulnumarasi.matches(okulNumarasiDeseni)) {
        JOptionPane.showMessageDialog(this, "Okul numarası yalnızca sayılardan oluşmalıdır!", "Hata", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!kullaniciadi.matches(kullaniciAdiDeseni)) {
        JOptionPane.showMessageDialog(this, "Kullanıcı adı özel karakter içeremez!", "Hata", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!sifre.matches(sifreDeseni)) {
        JOptionPane.showMessageDialog(this, "Şifre en az 3 karakterden oluşmalıdır!", "Hata", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!email.matches(emailDeseni)) {
        JOptionPane.showMessageDialog(this, "Okul mail adresi '@stu.fsm.edu.tr' ile bitmelidir!", "Hata", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Okul numarasının eşsizliğini kontrol et
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/canteen?user=root&password= ");
        String query = "SELECT COUNT(*) FROM kayitolma WHERE okulnumarasi = ?";
        PreparedStatement pstmt = conn.prepareStatement(query);
        pstmt.setString(1, okulnumarasi);
        ResultSet rs = pstmt.executeQuery();

        if (rs.next() && rs.getInt(1) > 0) {
            JOptionPane.showMessageDialog(this, "Okul numarası zaten mevcut! Lütfen farklı bir numara giriniz.", "Hata", JOptionPane.ERROR_MESSAGE);
            rs.close();
            pstmt.close();
            conn.close();
            return;
        }

        rs.close();
        pstmt.close();
        conn.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Veritabanı hatası: " + ex.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Eğer tüm doğrulamalar geçerse veritabanına kullanıcı eklenir
    boolean isadded = KullanıcıEkle(okulnumarasi, kullaniciadi, sifre, email, kayitolmaturu);

    if (isadded) {
        JOptionPane.showMessageDialog(rootPane, "Kullanıcı başarıyla eklendi!");
    } else {
        JOptionPane.showMessageDialog(rootPane, "Kullanıcı eklenemedi. Lütfen tekrar deneyin.", "Hata", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Giriş ekranına yönlendirme
    girisyap girisFrame = new girisyap();
    girisFrame.setLocationRelativeTo(null);
    girisFrame.setVisible(true);
    this.dispose(); // Mevcut pencereyi kapat
    }//GEN-LAST:event_kayitolbutonuActionPerformed

    private void comboboxturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxturActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxturActionPerformed

    private void okulnumarasitxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okulnumarasitxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okulnumarasitxtActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         girisyap girisFrame = new girisyap();
    girisFrame.setLocationRelativeTo(null);
    girisFrame.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kayitol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kayitol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kayitol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kayitol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kayitol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboboxtur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kayitolbutonu;
    private javax.swing.JTextField kullaniciaditxt;
    private javax.swing.JTextField mailadresitxt;
    private javax.swing.JTextField okulnumarasitxt;
    private javax.swing.JTextField sifretxt;
    // End of variables declaration//GEN-END:variables
}

