/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2proje;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yusuf
 */
public class odemesayfasi extends javax.swing.JFrame {
    private final Object[][] sepetBilgileri;
    private final double toplamFiyat;
    private String kullaniciTuru;
    /**
     * Creates new form odemesayfasi
     */

    
    public odemesayfasi(Object[][] sepetBilgileri, double toplamFiyat, String kullaniciTuru) {
    this.sepetBilgileri = sepetBilgileri;
    this.toplamFiyat = toplamFiyat;
    this.kullaniciTuru = kullaniciTuru; // Kullanıcı türünü ata
    initComponents();
    sepetBilgileriniYukle(); 
}
    private void sepetBilgileriniYukle() {
        DefaultTableModel model = (DefaultTableModel) sepetTable.getModel();
        for (Object[] row : sepetBilgileri) {
            model.addRow(row);
        }
    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        odemeyapbutonu = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sepetTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Ödeme Yöntemi Seçin");

        odemeyapbutonu.setBackground(new java.awt.Color(0, 51, 153));
        odemeyapbutonu.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        odemeyapbutonu.setForeground(new java.awt.Color(255, 255, 255));
        odemeyapbutonu.setText("Ödeme Yap");
        odemeyapbutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odemeyapbutonuActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Kredi Kartı");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Nakit");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        sepetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(sepetTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(odemeyapbutonu, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 68, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jRadioButton2)
                        .addGap(39, 39, 39)
                        .addComponent(odemeyapbutonu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void odemeyapbutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odemeyapbutonuActionPerformed
    // Siparişi onaylama ve stokları güncelleme
    Connection conn = null;
    PreparedStatement pstmt = null;
    PreparedStatement pstmtInsert = null;

    try {
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/canteen?user=root&password=elbiz-2221221040");

        // Ödeme yöntemi kontrolü
        String odemeYontemi = "";
        if (jRadioButton1.isSelected()) {
            odemeYontemi = "Nakit";
        } else if (jRadioButton2.isSelected()) {
            odemeYontemi = "Kredi Kartı";
        } else {
            JOptionPane.showMessageDialog(this, "Lütfen bir ödeme yöntemi seçin!", "Hata", JOptionPane.ERROR_MESSAGE);
            return; // Ödeme yöntemi seçilmezse işlemi durdur
        }

        // Sepet kontrolü
        if (sepetBilgileri == null || sepetBilgileri.length == 0) {
            JOptionPane.showMessageDialog(this, "Sepetiniz boş. Lütfen ürün ekleyin!", "Hata", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Stokları güncelleme
        String updateQuery = "UPDATE urunlistesi SET urunadedi = urunadedi - ? WHERE urunadi = ?";
        pstmt = conn.prepareStatement(updateQuery);

        for (Object[] urun : sepetBilgileri) {
            String urunAdi = (String) urun[0]; // Ürün adı
            int siparisAdedi = (int) urun[2]; // Sipariş adedi

            pstmt.setInt(1, siparisAdedi);
            pstmt.setString(2, urunAdi);
            pstmt.addBatch(); // Batch işlemi için ekle
        }

        pstmt.executeBatch(); // Stok güncellemelerini çalıştır

        // Fatura tablosuna ekleme
        String insertQuery = "INSERT INTO fatura (urunadi, urunmiktari, odemeyontemi, toplamfiyat) VALUES (?, ?, ?, ?)";
        pstmtInsert = conn.prepareStatement(insertQuery);

        for (Object[] urun : sepetBilgileri) {
            String urunAdi = (String) urun[0];
            int urunMiktari = (int) urun[2];
            double toplamFiyat = (double) urun[1];

            pstmtInsert.setString(1, urunAdi);
            pstmtInsert.setInt(2, urunMiktari);
            pstmtInsert.setString(3, odemeYontemi);
            pstmtInsert.setDouble(4, toplamFiyat);
            pstmtInsert.addBatch(); // Batch işlemine ekle
        }

        pstmtInsert.executeBatch(); // Fatura kayıtlarını ekle

        JOptionPane.showMessageDialog(this, "Siparişiniz başarıyla onaylandı!", "Başarılı", JOptionPane.INFORMATION_MESSAGE);

        // Kullanıcı türüne göre işlem
        if ("admin".equals(kullaniciTuru)) {
            Faturasayfasi faturasayfasiFrame = new Faturasayfasi(kullaniciTuru); // Kullanıcı türünü aktar
            faturasayfasiFrame.setLocationRelativeTo(null);
            faturasayfasiFrame.setVisible(true);
        } else if ("standart".equals(kullaniciTuru)) {
            JOptionPane.showMessageDialog(this, "Sipariş süreci tamamlandı. Program kapatılıyor.", "Bilgilendirme", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0); // Programı kapat
        }

        this.dispose(); // Mevcut pencereyi kapat

    } catch (SQLException ex) {
        ex.printStackTrace(); // Hata detaylarını konsola yazdır
        JOptionPane.showMessageDialog(this, "Veritabanı hatası: " + ex.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
    } finally {
        try {
            if (pstmtInsert != null) pstmtInsert.close();
            if (pstmt != null) pstmt.close();
            if (conn != null) conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Bağlantı kapatılırken hata oluştu: " + ex.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }

    }//GEN-LAST:event_odemeyapbutonuActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(odemesayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(odemesayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(odemesayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(odemesayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Test verileri oluştur
            Object[][] sepetBilgileri = {
                {"Ürün 1", 50.0, 2},
                {"Ürün 2", 30.0, 1},
                {"Ürün 3", 120.0, 4}
            };
            double toplamFiyat = 50.0 + 30.0 + 120.0; // Test toplam fiyatı

            // Ödeme sayfasını test etmek için constructor'a test verileri gönder
            new odemesayfasi(sepetBilgileri, toplamFiyat, "standart").setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton odemeyapbutonu;
    private javax.swing.JTable sepetTable;
    // End of variables declaration//GEN-END:variables
}